### ISSUE TITLE
loading text file or json not working

### ISSUE THREAD

**Issue by mmkodali** [cslarsen/wpm#17]
loading text file or json as suggested in readme is giving following output.

Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/2.7.10/bin/wpm", line 11, in <module>
    wpm.commandline.main()
  File "/home/murali/.pyenv/versions/2.7.10/lib/python2.7/site-packages/wpm/commandline.py", line 130, in main
    with wpm.game.Game(quotes, stats) as game:
  File "/home/murali/.pyenv/versions/2.7.10/lib/python2.7/site-packages/wpm/game.py", line 246, in __init__
    self.quotes = quotes.random_iterator()
AttributeError: 'list' object has no attribute 'random_iterator'

**Comment by cslarsen** [comment]
Thanks for the report, I'll fix it.

**Comment by cslarsen** [comment]
JSON-loading fixed in 4325abcab9b2afc988e6221c0e1c2d60cf65e8fc

**Comment by cslarsen** [comment]
Text-loading fixed in e54d68bb95dabe0423881ac29ed03949ea2cd3b2
