### ISSUE TITLE
not working on windows wint mingw64 console

### ISSUE THREAD

**Issue by matsonkepson** [cslarsen/wpm#36]
Trerminal windows 10 > MINGW64
$ python --version
Python 3.6.5

$ python -m wpm
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\temp\wpm\wpm\__main__.py", line 14, in <module>
    import wpm.commandline
  File "C:\temp\wpm\wpm\commandline.py", line 22, in <module>
    import wpm.config
  File "C:\temp\wpm\wpm\config.py", line 14, in <module>
    import curses
  File "C:\Python36\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by matsonkepson** [comment]
```
$ wpm

Redirection is not supported.
```

**Comment by cslarsen** [comment]
I don't own a Windows system, so I can't look into this. But you can probably google it and find out if curses is fully supported on the windows command shell like you're using. By "fully" I mean that all the attributes and stuff are translated (in theory, I guess it should work just fine, but it may not be so in practice).

**Comment by matsonkepson** [comment]
heh, I will try :)

What I can add from my side that I was trying to run it in PowerShell/cmd but it is exiting with the same exit error

> PS C:\temp\wpm> python -m wpm
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\temp\wpm\wpm\__main__.py", line 17, in <module>
    wpm.commandline.main()
  File "C:\temp\wpm\wpm\commandline.py", line 237, in main
    with wpm.game.GameManager(quotes, stats, opts.cpm) as gm:
  File "C:\temp\wpm\wpm\game.py", line 45, in __init__
    self.screen = Screen()
  File "C:\temp\wpm\wpm\screen.py", line 70, in __init__
    self.set_colors()
  File "C:\temp\wpm\wpm\screen.py", line 153, in set_colors
    hicolor = os.getenv("TERM").endswith("256color")
AttributeError: 'NoneType' object has no attribute 'endswith'


Also was able to get the first screen by the https://conemu.github.io/ soft but after typing the first letter i got this

> C:\temp\wpm (master -> origin)
λ python -m wpm
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\temp\wpm\wpm\__main__.py", line 17, in <module>
    wpm.commandline.main()
  File "C:\temp\wpm\wpm\commandline.py", line 239, in main
    gm.run(to_front=text_ids)
  File "C:\temp\wpm\wpm\game.py", line 99, in run
    head = self.get_stats(self.elapsed)
  File "C:\temp\wpm\wpm\game.py", line 162, in get_stats
    "%5.1f wpm" % self.wpm(elapsed),
  File "C:\temp\wpm\wpm\game.py", line 128, in wpm
    return min((60.0 * self.position / 5.0) / elapsed, 999)
ZeroDivisionError: float division by zero

**Comment by cslarsen** [comment]
Yeah, the hicolor part is very unix specific, so just skip those TERM parts. As to div by zero, seems elapsed doesn't have a value. Just return any float value there while testing (or check if elapsed is zero).

**Comment by idanpa** [comment]
Hi @cslarsen, thank you for publishing this application!
Managed to get it working on native windows, could you please review #47?
