### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by M5oul** [cslarsen/wpm#39]
Hi, and thanks for this nice tool.
When typing, I crashed the program while clicking on space or alt:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/wpm", line 13, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/wpm/commandline.py", line 239, in main
    gm.run(to_front=text_ids)
  File "/usr/local/lib/python3.6/site-packages/wpm/game.py", line 111, in run
    key)
  File "/usr/local/lib/python3.6/site-packages/wpm/screen.py", line 485, in show_keystroke
    self.update_prompt("> " + typed)
  File "/usr/local/lib/python3.6/site-packages/wpm/screen.py", line 354, in update_prompt
    Screen.COLOR_PROMPT)
  File "/usr/local/lib/python3.6/site-packages/wpm/screen.py", line 270, in addstr
    self.window.addstr(y_pos, x_pos, text, color)
ValueError: embedded null byte
```

 I am not able to reproduce it.

**Comment by cslarsen** [comment]
OK, I'm not aware of any typical keypresses that produces embedded null bytes. Would be nice if you or anyone else could find a way to reproduce this. Perhaps a mouse click with mouse enabled terminal?

Will need to think about this one.

**Comment by cslarsen** [comment]
No activity, closing issue.
