### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by VibSel** [cslarsen/wpm#48]
When I type `wpm` or `python -m wpm` I get this error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/wpm/__main__.py", line 14, in <module>
    import wpm.commandline
  File "/usr/local/lib/python2.7/dist-packages/wpm/commandline.py", line 27, in <module>
    import wpm.quotes
  File "/usr/local/lib/python2.7/dist-packages/wpm/quotes.py", line 23, in <module>
    import pkg_resources
ImportError: No module named pkg_resources`

**Comment by cslarsen** [comment]
How did you install wpm?

Most likely I should add `setuptols` to the requirements.

See https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources and let me know if installing setuptools fixes this problem.

**Comment by cslarsen** [comment]
I've added setuptoos to install_requires in setup.py
